{% set name = "ipe" %}
{% set version = "7.2.25" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/otfried/ipe/releases/download/v{{ version }}/ipe-{{ version }}-src.tar.gz
  sha256: bfca2bfbd2119e4c0a310f361077bc2efb1f5b95e34275d1a02b8ade7aba21fc

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - make
    - pkg-config
    - autoconf
    - automake
    - libtool
    - doxygen
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - qt-main
    - gsl
    - zlib
    - freetype
    - cairo
    - libpng
    - libjpeg-turbo
    - libspiro
    - lua
    - hicolor-icon-theme
    - poppler
    - libblas
    - libcblas
  run:
    - qt-main
    - enchant
    - qt-main
    - gsl
    - zlib
    - freetype
    - cairo
    - libpng
    - libjpeg-turbo
    - libspiro
    - lua
    - hicolor-icon-theme
    - poppler
    - curl

test:
  commands:
    - test -f $PREFIX/bin/ipe  # [unix]

about:
  home: https://ipe.otfried.org/
  license: GPL-3.0-only
  license_family: GPL3
  license_file: COPYING
  summary: Ipe is a drawing editor for creating figures in PDF format.

extra:
  recipe-maintainers:
    - izahn
